### ISSUE TITLE
Configuration modification for Lazy load JS files

### ISSUE THREAD

**Issue by dhirenipatel** [aaronallport/generator-angular-require#48]
I am creating a enterprise level application. Evaluating your generator to lazy load the js files whenever required. 

I saw in your sample app, in that all files are loaded on the first page request itself. Well, in Enterprise level application that should not be the case. JS should get loaded whenever require. 

How can I modify Grunt or Code so that JS files will get requested from server whenever require not in the one go.

**Comment by aaronallport** [comment]
To do that you'll have to bundle up the code you need by using require config files so that you bundle up different pages or functional application areas as needed and then call them in on a per-required basis.

This generator is opinionated towards bundling up JavaScript, minifying and loading at app startup.

If you have a specific use-case, please share details and I'd be happy to help you.

Thanks,

Aaron
